# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basicapp.Tag'),
        ),
    ]
